apiVersion: v1
kind: Service
metadata:
  name: express-mysql-db
  namespace: vue-expressjs-crud
spec:
  selector:
    app: vue-expressjs-crud-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer